/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: charles.cla (https://sketchfab.com/charles.cla)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/books-collection-66e06a66662a4fa5936d6a9b234926c0
Title: Books Collection
*/

import React, { useState, forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export const Books = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('/models/books.glb')
  const [hovered, setHovered] = useState(false)
  const [scale, setScale] = useState(1)

  useFrame(() => {
    setScale((prev) => {
      const target = hovered ? 1.15 : 1
      return prev + (target - prev) * 0.1
    })
  })

  return (
    <group
      {...props}
      ref={ref}
      dispose={null}
      scale={Array.isArray(props.scale) ? props.scale.map((s) => s * scale) : scale}
      onPointerOver={() => setHovered(true)}
      onPointerOut={() => setHovered(false)}
      onPointerDown={() => setHovered(true)}
      onPointerUp={() => setHovered(false)}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.material_0}
        rotation={[-Math.PI / 2, 0, 0]}
        lightIntensity={30}
        lightColor={0x000000}
        lightPosition={[0, 0, 0]}
        lightDistance={100}
        lightDecay={2}
        lightShadowMapSize={1024}
        lightShadowMapBias={0.001}
        lightShadowMapSoft={true}
        lightShadowMapBlurSamples={10}
        lightShadowMapBlurSize={10}
      />
    </group>
  )
})

useGLTF.preload('/models/books.glb')
